import { SongTrending } from "src/component/Item/interface";
export const DATA_ALBUMS: SongTrending[] = [
  {
    nameSong: "Sorfcore",
    nameSinger: "The neighberhood",
    id: 0,
    playtime: 206,
    dateRelease: "Nov 4, 2023",
    src: require("src/assets/images/trendSong/softcore.png"),
    description: "Hard to Imagine the Neighbourhood Ever Changing",
  },
  {
    nameSong: "Skyfall Beats",
    nameSinger: "nightmares",
    id: 1,
    playtime: 100,
    dateRelease: "Oct 26, 2023",
    src: require("src/assets/images/trendSong/sky_fall_beats.png"),
    description: "nightmares",
  },
  {
    nameSong: "Greedy",
    nameSinger: "tate mcrae",
    id: 2,
    playtime: 100,
    dateRelease: "Dec 30, 2023",
    src: require("src/assets/images/trendSong/greedy.png"),
    description: "Greedy",
  },
  {
    nameSong: "Lovin On me",
    nameSinger: " jack harlow",
    id: 3,
    playtime: 100,
    dateRelease: "Dec 30, 2023",
    src: require("src/assets/images/trendSong/lovin_on_me.png"),
    description: "Lovin On me",
  },
  {
    nameSong: "pain the town red",
    nameSinger: "Doja Cat",
    id: 4,
    playtime: 100,
    dateRelease: "Dec 29, 2023",
    src: require("src/assets/images/trendSong/pain_the_town_red.png"),
    description: "Paint The Town Red",
  },
  {
    nameSong: "Dancin On Night",
    nameSinger: "Dualipa",
    id: 5,
    playtime: 100,
    dateRelease: "May 27, 2023",
    src: require("src/assets/images/trendSong/dancin_on_night.png"),
    description: "Dance The Night(From Barbie Movie)",
  },
  {
    nameSong: "Water",
    nameSinger: "Tyla",
    id: 6,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/trendSong/water.png"),
    description: "Water",
  },
  {
    nameSong: "Push your limits",
    nameSinger: "Brian michael",
    id: 7,
    playtime: 144,
    dateRelease: "Jan 2, 2024",
    src: require("src/assets/images/albums/push_your_limit.png"),
    description: "Push your limits",
  },
  {
    nameSong: "Houdini",
    nameSinger: "Dualipa",
    id: 8,
    playtime: 185,
    dateRelease: "Dec 12, 2023",
    src: require("src/assets/images/albums/houdini.png"),
    description: "Houdini",
  },
  {
    nameSong: "Lala",
    nameSinger: "mykw towers",
    id: 9,
    playtime: 197,
    dateRelease: "Nov 20, 2023",
    src: require("src/assets/images/albums/lala.png"),
    description: "La vida es una",
  },

  {
    nameSong: "I Wanaa Be Yours",
    nameSinger: "Tyla",
    id: 10,
    playtime: 100,
    dateRelease: "Sep 9, 2023",
    src: require("src/assets/images/albums/i_wanna_be_your.png"),
    description: "AM",
  },
  {
    nameSong: "Paradise",
    nameSinger: "braaheim",
    id: 11,
    playtime: 150,
    dateRelease: "Jul 5, 2023",
    src: require("src/assets/images/albums/paradise.png"),
    description: "Paradise",
  },
  {
    nameSong: "As It Was",
    nameSinger: "Harry Styles",
    id: 12,
    playtime: 167,
    dateRelease: "Sep 14, 2022",
    src: require("src/assets/images/albums/as_it_was.png"),
    description: "As It Was",
  },
  {
    nameSong: "Another Love",
    nameSinger: "Tyla",
    id: 13,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/another_love.png"),
    description: "Water",
  },
  {
    nameSong: "Daylight",
    nameSinger: "Tyla",
    id: 14,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/daylight.png"),
    description: "Water",
  },
  {
    nameSong: "Beggin",
    nameSinger: "Tyla",
    id: 15,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/beggin.png"),
    description: "Water",
  },
  {
    nameSong: "What Was I Made Function",
    nameSinger: "Tyla",
    id: 16,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/what-was_i_made.png"),
    description: "Water",
  },
  {
    nameSong: "Daddy Issues",
    nameSinger: "Tyla",
    id: 17,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/daddy_issues.png"),
    description: "Water",
  },
  {
    nameSong: "Rolling In The Deep",
    nameSinger: "Tyla",
    id: 18,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/rolling_in_the_deep.png"),
    description: "Water",
  },
  {
    nameSong: "OneShot",
    nameSinger: "Tyla",
    id: 19,
    playtime: 100,
    dateRelease: "Dec 10, 2023",
    src: require("src/assets/images/albums/one_shot.png"),
    description: "Water",
  },
];
